<?php

/**
 * @file
 *   Main file for hooks.
 */

define('JSLD_MATCH_TYPE_LISTED', 1);
define('JSLD_MATCH_TYPE_UNLISTED', 2);


/**
 * Add data to current.
 *
 * @todo move to helper.
 * 
 * @param array $data
 *   Array with Json-LD data structure.
 */
function jsld_push_data($data = []) {
  global $jsld;
  $jsld[] = $data;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function jsld_preprocess_page(&$variables) {
  $plugin_service = \Drupal::service('plugin.manager.jsld.entity');
  foreach ($plugin_service->getDefinitions() as $plugin_id => $plugin) {
    $instance = $plugin_service->createInstance($plugin_id);
    // @TODO.
  }
}
